site_name: SKYEYE'S HOMEPAGE # 显示在左上角

nav:
  
  - Home:
    
    - index.md
    
  - 课程笔记:
    - 最简系列:
      - 课程笔记/最简系列/最简马原.md
      - 课程笔记/最简系列/最简复变.md
      - 课程笔记/最简系列/最简大物2.md
    - 电路:
      - 课程笔记/电路模电/直流电路.md
      - 课程笔记/电路模电/正弦交流电路.md
      - 课程笔记/电路模电/过渡过程.md
    - 模电:
      - 课程笔记/电路模电/非线性器件.md
      - 课程笔记/电路模电/放大电路.md
      - 课程笔记/电路模电/信号发生电路和功率变换电路.md
    - 其他:
      - 课程笔记/其他/保留计划.md
  - 公开项目:
    - 公开项目/SQTP.md
    - 公开项目/iGEM.md
  - 理论:
    - 理论/大学OVERALLCHECK.md
    - 理论/高考后感言.md
  - 友链:
    - link.md


theme:
  name: material # 主题
  # custom_dir: overrides
  palette:
    scheme: skyeye # 用的是extra.css里定义的skyeye scheme

# 本来可以做一个颜色切换但是我懒得搞了
# # Light mode
#   - scheme: default
#     toggle:
#       icon: material/weather-sunny
#       name: Switch to dark mode

#   # Dark mode
#   - scheme: slate
#     toggle:
#       icon: material/weather-night
#       name: Switch to light mode

  font: false # 要求按照extra.css里的来，不要搞默认的字体

  language: zh # 中文网站

  logo: https://skyeyesandox-1374084537.cos.ap-shanghai.myqcloud.com/202508141305660.webp # 左上角图标显示的
  favicon: https://skyeyesandox-1374084537.cos.ap-shanghai.myqcloud.com/202508141305660.webp #标签页的图标

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

# edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/skyeye-2025/Home # 右上角点击跳转的链接
repo_name: skyeye-2025/Home # 右上角的名字

plugins:
  - search # 搜索框
  - tags
  # - statistics # 统计字数的，这个要在ci.yml里加一段pip install的命令

extra:
  generator: false # 不显示made with mkdocs
  # 个人链接，最下面显示的
  social:
    # - icon: fontawesome/brands/weixin
    #   link: https://s1.imagehub.cc/images/2024/02/02/bb9ee71b03ee7a3b87caad5cc4bcebff.jpeg
    #   name: Wechat
    - icon: fontawesome/brands/github
      link: https://github.com/skyeye-2025
    - icon: fontawesome/regular/envelope #联系方式图标
      link: mailto:<skyeye2022@163.com> #邮件联系方式
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/441014286
      
markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr # 显示缩写，但是不太好用
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.arithmatex: # 支持latex
      generic: true
  - toc: # 显示侧边导航，即本文目录
      permalink: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/typewriter.js
  # - "//api.busuanzi.cc/static/3.6.9/busuanzi.min.js"
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.staticfile.org/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/typewriter.css
  - stylesheets/flink.css